### PR TITLE
Sliding Window Maximum

### LINKED ISSUE #66: [PROG] Sliding Window Maximum
**Program Description**
You are given an array of integers nums, there is a sliding window of size k which is moving from the very left of the array to the very right. You can only see the k numbers in the window. Each time the sliding window moves right by one position.

Return the max sliding window.

**Additional context**
Input: nums = [1,3,-1,-3,5,3,6,7], k = 3
Output: [3,3,5,5,6,7]

**Checklist**
- [x] This issue has not been mentioned in existing issues.

### PR DESCRIPTION
**Pull request by harshita9621**
#### Checklist

- [x] Added description of change.
- [x] I acknowledge that all my contributions will be made under the project's license.

**Program Request** 
- [x] Added file name matches **File name guidelines** mentioned in [Contributing guidelines](https://github.com/GDSC-AUM/OpenOcto-DSA/blob/main/CONTRIBUTING.md)
- [x] Updated documentation OR created an issue for someone else to update the documentation.

**Bug Fix** 
- [x] Bug is now fixed and program now behaves as expected.

**Documentation Update** 
- [x] Documenation matches **format** mentioned in [Contributing guidelines](https://github.com/GDSC-AUM/OpenOcto-DSA/blob/main/CONTRIBUTING.md)
- [x] If applicable, referenced sources have been linked.

**Program Improvement**
- [x] The improvements made are not just visual and actually makes the program more efficient. 

Notes: This is with respect to issue #66

### CODE REVIEW

**Comment by harshita9621** [comment]
@saaimsid Review this PR.

**Comment by saaimsid** [comment]
@harshita9621  Kindly contact the project maintainers.

**Review by unshDee — APPROVED** [review]

**Comment by harshita9621** [comment]
@unshDee When my PR get mature beacause fest going to end today

**Comment by unshDee** [comment]
> @unshDee When my PR get mature beacause fest going to end today

Hello @harshita9621 I had already approved this PR and merged it around 2 weeks ago. 
It's visible above.

**Pull request merged**
