### PR TITLE
Prims Algorithm Added

### LINKED ISSUE #20: [PROG] Prim's Algorithm
**Program Description**
Program to implement Prim's Algorithm.

**Additional**
Update the documentation (`DOC.md` in `greedy` folder) to include Prim's Algorithm.

**Checklist**
- [x] This issue has not been mentioned in existing issues.

### PR DESCRIPTION
**Pull request by ajay-makvana**
#### What was changed?
Issue #20 Solved 
Prims Algorithm Added

#### Checklist

- [x] Added description of change.
- [x] I acknowledge that all my contributions will be made under the project's license.

**Program Request** 
- [X] Updated documentation OR created an issue for someone else to update the documentation.

**Documentation Update** 
- [X] Documenation matches **format** mentioned in [Contributing guidelines](https://github.com/GDSC-AUM/OpenOcto-DSA/blob/main/CONTRIBUTING.md)
- [X] If applicable, referenced sources have been linked.

**Program Improvement**
- [X] The improvements made are not just visual and actually makes the program more efficient. 

Prims Algorithm Added

### CODE REVIEW

**Review by unshDee — CHANGES_REQUESTED** [review]
Hello @ajay-makvana the file name doesn't follow the file name guidelines!
Please refer that and make the necessary changes. Also if possible update the `DOC.md` file too.

**Review by ajay-makvana — COMMENTED** [review]
file name changed as suggested

**Review by unshDee — CHANGES_REQUESTED** [review]
Hello @ajay-makvana the file name still doesn't follow the guidelines.
The name should be in lowercase only, words to be separated by spaces.
I suggest you name this file as `prims_algorithm.cpp`

**Review by unshDee — APPROVED** [review]
Done!

**Pull request merged**
