### PR TITLE
Add ternary search

### LINKED ISSUE #49: [PROG] Ternary Search
**Program Description**
Program to implement Ternary Search

**Additional**
Update the documentation (`DOC.md` in `searching` folder)

**Checklist**
- [x] This issue has not been mentioned in existing issues.

### PR DESCRIPTION
**Pull request by akulagrawal**
#### Checklist

- [x] Added description of change.
- [x] I acknowledge that all my contributions will be made under the project's license.

**Program Request** 
- [x] Added file name matches **File name guidelines** mentioned in [Contributing guidelines](https://github.com/GDSC-AUM/OpenOcto-DSA/blob/main/CONTRIBUTING.md)
- [x] Updated documentation OR created an issue for someone else to update the documentation.

Notes:

### CODE REVIEW

**Review by unshDee — CHANGES_REQUESTED** [review]
@akulagrawal change the header from `bits/stdc++.h` to the ones which were actually used in the program. Also, change the file name from `ternarysearch.cpp` to `ternary_search.cpp` to improve readability.

**Comment by unshDee** [comment]
Also, @akulagrawal remove the https://github.com/GDSC-AUM/OpenOcto-DSA/issues/46 issue from the linked issues as the person who made the issue closed it and I can't make changes to it.
I've already created a new issue and linked it to your PR so removing the older one shouldn't be a problem

**Comment by akulagrawal** [comment]
@unshDee updated

**Review by unshDee — APPROVED** [review]
Done!

**Pull request merged**
