### PR TITLE
Added Prime Factor of a number

### LINKED ISSUE #23: [PROG] Prime Factors
**Program Description**
Program to display prime factors of a number

**Additional context**
Update documentation (`DOC.md` in `mathematics` folder).

**Checklist**
- [x] This issue has not been mentioned in existing issues.

### PR DESCRIPTION
**Pull request by saaimsid**
#### Checklist

- [x] Added description of change.
- [x] I acknowledge that all my contributions will be made under the project's license.

**Program Request** 
- [x] Added file name matches **File name guidelines** mentioned in [Contributing guidelines](https://github.com/GDSC-AUM/OpenOcto-DSA/blob/main/CONTRIBUTING.md)
- [x] Updated documentation OR created an issue for someone else to update the documentation.

**Documentation Update** 
- [x] Documenation matches **format** mentioned in [Contributing guidelines](https://github.com/GDSC-AUM/OpenOcto-DSA/blob/main/CONTRIBUTING.md)
- [x] If applicable, referenced sources have been linked.

Notes: Added Prime Factor of a number

### CODE REVIEW

**Comment by unshDee** [comment]
@saaimsid 
The documentation you added doesn't match with the program you added, document contains description of factors of a number while the program is for prime factors of a number.
Please correct the documentation.

Also there seems to be a bug where the program displays all prime factors of the number once expect for 2 which is displayed multiple times. Please fix this too.

**Review by unshDee — CHANGES_REQUESTED** [review]
Please refer the comments I made earlier and make the appropriate changes

**Comment by saaimsid** [comment]
Hey @unshDee! I have updated the changes. Kindly review them.

**Review by unshDee — APPROVED** [review]
Approved! Thanks for changing according to the pointers provided😁

**Pull request merged**
